language: ruby
rvm:
 - 2.6.3
script:
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - rdoc app
 - bundle exec bundle-audit update && bundle exec bundle-audit check
 - bundle exec rake test